package com.coder.decimetrixandroidtest.domain.model

import com.coder.decimetrixandroidtest.data.model.entities.LocationEntity
import com.coder.decimetrixandroidtest.data.model.locationModelResponse.PropertiesDto

data class DomainLocation(
    val adm0_a3: String? = null,
    val adm0cap: Int? = null,
    val adm0name: String? = null,
    val adm1name: String? = null,
    val capalt: Int? = null,
    val capin: Any? = null,
    val changed: Int? = null,
    val checkme: Int? = null,
    val diffascii: Int? = null,
    val diffnote: String? = null,
    val featureclass: String? = null,
    val geonameid: Int? = null,
    val iso_a2: String? = null,
    val labelrank: Int? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val ls_match: Int? = null,
    val ls_name: Any? = null,
    val megacity: Int? = null,
    val meganame: Any? = null,
    val name: String? = null,
    val namealt: Any? = null,
    val nameascii: String? = null,
    val namediff: Int? = null,
    val namepar: Any? = null,
    val natscale: Int? = null,
    val note: Any? = null,
    val pop_max: Int? = null,
    val pop_min: Int? = null,
    val pop_other: Int? = null,
    val rank_max: Int? = null,
    val rank_min: Int? = null,
    val scalerank: Int? = null,
    val sov0name: String? = null,
    val sov_a3: String? = null,
    val worldcity: Int? = null,
    val favorite: Boolean? = null
)

fun PropertiesDto.toDomain() : DomainLocation = DomainLocation(
    this.adm0A3,
    this.adm0cap,
    this.adm0name,
    this.adm1name,
    this.capalt,
    this.capin,
    this.changed,
    this.checkme,
    this.diffascii,
    this.diffnote,
    this.featureclass,
    this.geonameid,
    this.isoA2,
    this.labelrank,
    this.latitude,
    this.longitude,
    this.lsMatch,
    this.lsName,
    this.megacity,
    this.meganame,
    this.name,
    this.namealt,
    this.nameascii,
    this.namediff,
    this.namepar,
    this.natscale,
    this.note,
    this.popMax,
    this.popMin,
    this.popOther,
    this.rankMax,
    this.rankMin,
    this.scalerank,
    this.sov0name,
    this.sovA3,
    this.worldcity,
    this.favorite
)

fun LocationEntity.toDomain() = DomainLocation(
    name = this.location,
    longitude =  this.latitud,
    latitude =  this.longitud,
    favorite =  this.favorite
)